# Generated by Django 4.2.10 on 2024-02-14 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='fanlar',
            options={'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='shartnoma',
            options={'verbose_name_plural': 'Shartnomalar'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.teachers'),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='tugash_sanasi',
            field=models.DateField(default=datetime.datetime(2024, 5, 24, 14, 31, 37, 687891, tzinfo=datetime.timezone.utc)),
        ),
    ]
